master:
  build: logstashmaster
  ports:
    - 9200:9200
    - 9300:9300
    - 5601:5601
  volumes_from:
    - certs
  environment:
    LOGSTASH_DOMAIN: logstashhostname

forward:
  build: logstashforwarder
  volumes_from:
    - certs
  volumes:
    - logstashforwarder/logexamples:/var/log/apache
  links:
    - master:logstashhostname
  environment:
    MASTER: logstashhostname

certs:
  image: debian
  volumes:
    - /certs
